// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sarchlab/mgpusim/v3/mem/vm/tlb/internal (interfaces: Set)

package tlb

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	vm "github.com/sarchlab/mgpusim/v3/mem/vm"
)

// MockSet is a mock of Set interface.
type MockSet struct {
	ctrl     *gomock.Controller
	recorder *MockSetMockRecorder
}

// MockSetMockRecorder is the mock recorder for MockSet.
type MockSetMockRecorder struct {
	mock *MockSet
}

// NewMockSet creates a new mock instance.
func NewMockSet(ctrl *gomock.Controller) *MockSet {
	mock := &MockSet{ctrl: ctrl}
	mock.recorder = &MockSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSet) EXPECT() *MockSetMockRecorder {
	return m.recorder
}

// Evict mocks base method.
func (m *MockSet) Evict() (int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evict")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Evict indicates an expected call of Evict.
func (mr *MockSetMockRecorder) Evict() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evict", reflect.TypeOf((*MockSet)(nil).Evict))
}

// Lookup mocks base method.
func (m *MockSet) Lookup(arg0 vm.PID, arg1 uint64) (int, vm.Page, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(vm.Page)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Lookup indicates an expected call of Lookup.
func (mr *MockSetMockRecorder) Lookup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockSet)(nil).Lookup), arg0, arg1)
}

// Update mocks base method.
func (m *MockSet) Update(arg0 int, arg1 vm.Page) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", arg0, arg1)
}

// Update indicates an expected call of Update.
func (mr *MockSetMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSet)(nil).Update), arg0, arg1)
}

// Visit mocks base method.
func (m *MockSet) Visit(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Visit", arg0)
}

// Visit indicates an expected call of Visit.
func (mr *MockSetMockRecorder) Visit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Visit", reflect.TypeOf((*MockSet)(nil).Visit), arg0)
}
