package main

var benchmarks = []benchmark{
	{
		benchmarkPath:  "../../benchmarks/polybench/atax",
		executablePath: "../../samples/atax",
		executable:     "atax",
		sizeArgs:       []string{"-x=256", "-y=256"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/polybench/bicg",
		executablePath: "../../samples/bicg",
		executable:     "bicg",
		sizeArgs:       []string{"-x=256", "-y=256"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/heteromark/fir",
		executablePath: "../../samples/fir",
		executable:     "fir",
		sizeArgs:       []string{"-length=8192"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/heteromark/aes",
		executablePath: "../../samples/aes",
		executable:     "aes",
		sizeArgs:       []string{"-length=16384"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/heteromark/kmeans",
		executablePath: "../../samples/kmeans",
		executable:     "kmeans",
		sizeArgs:       []string{"-points=1024", "-features=32", "-clusters=5", "-max-iter=5"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/heteromark/pagerank",
		executablePath: "../../samples/pagerank",
		executable:     "pagerank",
		sizeArgs:       []string{"-node=64", "-sparsity=0.5", "-iterations=2"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/amdappsdk/matrixmultiplication",
		executablePath: "../../samples/matrixmultiplication",
		executable:     "matrixmultiplication",
		sizeArgs:       []string{"-x=128", "-y=128", "-z=128"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/amdappsdk/matrixtranspose",
		executablePath: "../../samples/matrixtranspose",
		executable:     "matrixtranspose",
		sizeArgs:       []string{"-width=1024"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	// {
	// 	benchmarkPath:  "../../benchmarks/amdappsdk/bitonicsort",
	// 	executablePath: "../../samples/bitonicsort",
	// 	executable:     "bitonicsort",
	// 	sizeArgs:       []string{"-length=4096"},
	// 	cases: []benchmarkCase{
	// 		{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
	// 		{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
	// 		{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
	// 		{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
	// 		{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
	// 		{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
	// 		{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
	// 		{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
	// 		{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
	// 	},
	// },
	{
		benchmarkPath:  "../../benchmarks/amdappsdk/simpleconvolution",
		executablePath: "../../samples/simpleconvolution",
		executable:     "simpleconvolution",
		sizeArgs:       []string{},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/amdappsdk/floydwarshall",
		executablePath: "../../samples/floydwarshall",
		executable:     "floydwarshall",
		sizeArgs:       []string{},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/dnn/relu",
		executablePath: "../../samples/relu",
		executable:     "relu",
		sizeArgs:       []string{},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/shoc/bfs",
		executablePath: "../../samples/bfs",
		executable:     "bfs",
		sizeArgs:       []string{"-node=1024"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/shoc/stencil2d",
		executablePath: "../../samples/stencil2d",
		executable:     "stencil2d",
		sizeArgs:       []string{},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/shoc/spmv",
		executablePath: "../../samples/spmv",
		executable:     "spmv",
		sizeArgs:       []string{},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/shoc/fft",
		executablePath: "../../samples/fft",
		executable:     "fft",
		sizeArgs:       []string{"-MB=1"},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	{
		benchmarkPath:  "../../benchmarks/shoc/nbody",
		executablePath: "../../samples/nbody",
		executable:     "nbody",
		sizeArgs:       []string{},
		cases: []benchmarkCase{
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: false},
			{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: true, unifiedMemory: true},
			{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: true, unifiedMemory: true},
		},
	},
	// {
	// 	benchmarkPath:  "",
	// 	executablePath: "../../samples/concurrentkernel",
	// 	executable:     "concurrentkernel",
	// 	sizeArgs:       []string{},
	// 	cases: []benchmarkCase{
	// 		{gpus: []int{1}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 	},
	// },
	// {
	// 	benchmarkPath:  "",
	// 	executablePath: "../../samples/concurrentworkload",
	// 	executable:     "concurrentworkload",
	// 	sizeArgs:       []string{},
	// 	cases: []benchmarkCase{
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: false},
	// 		{gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: false},
	// {gpus: []int{1, 2, 3, 4}, timing: false, parallel: false, unifiedGPU: false, unifiedMemory: true},
	// {gpus: []int{1, 2, 3, 4}, timing: false, parallel: true, unifiedGPU: false, unifiedMemory: true},
	// {gpus: []int{1, 2, 3, 4}, timing: true, parallel: false, unifiedGPU: false, unifiedMemory: true},
	// {gpus: []int{1, 2, 3, 4}, timing: true, parallel: true, unifiedGPU: false, unifiedMemory: true},
	// },
	// },
}
