// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/akita/gcn3/timing (interfaces: CUComponent)

// Package mock_timing is a generated GoMock package.
package mock_timing

import (
	gomock "github.com/golang/mock/gomock"
	akita "gitlab.com/akita/akita"
	wavefront "gitlab.com/akita/gcn3/timing/wavefront"
	reflect "reflect"
)

// MockCUComponent is a mock of CUComponent interface
type MockCUComponent struct {
	ctrl     *gomock.Controller
	recorder *MockCUComponentMockRecorder
}

// MockCUComponentMockRecorder is the mock recorder for MockCUComponent
type MockCUComponentMockRecorder struct {
	mock *MockCUComponent
}

// NewMockCUComponent creates a new mock instance
func NewMockCUComponent(ctrl *gomock.Controller) *MockCUComponent {
	mock := &MockCUComponent{ctrl: ctrl}
	mock.recorder = &MockCUComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCUComponent) EXPECT() *MockCUComponentMockRecorder {
	return m.recorder
}

// AcceptWave mocks base method
func (m *MockCUComponent) AcceptWave(arg0 *wavefront.Wavefront, arg1 akita.VTimeInSec) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptWave", arg0, arg1)
}

// AcceptWave indicates an expected call of AcceptWave
func (mr *MockCUComponentMockRecorder) AcceptWave(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptWave", reflect.TypeOf((*MockCUComponent)(nil).AcceptWave), arg0, arg1)
}

// CanAcceptWave mocks base method
func (m *MockCUComponent) CanAcceptWave() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAcceptWave")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanAcceptWave indicates an expected call of CanAcceptWave
func (mr *MockCUComponentMockRecorder) CanAcceptWave() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAcceptWave", reflect.TypeOf((*MockCUComponent)(nil).CanAcceptWave))
}

// Flush mocks base method
func (m *MockCUComponent) Flush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Flush")
}

// Flush indicates an expected call of Flush
func (mr *MockCUComponentMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockCUComponent)(nil).Flush))
}

// IsIdle mocks base method
func (m *MockCUComponent) IsIdle() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsIdle")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsIdle indicates an expected call of IsIdle
func (mr *MockCUComponentMockRecorder) IsIdle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsIdle", reflect.TypeOf((*MockCUComponent)(nil).IsIdle))
}

// Run mocks base method
func (m *MockCUComponent) Run(arg0 akita.VTimeInSec) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockCUComponentMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCUComponent)(nil).Run), arg0)
}
