// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sarchlab/mgpusim/v4/amd/timing/cp/internal/resource (interfaces: CUResourcePool,CUResource)
//
// Generated by this command:
//
//	mockgen -destination mock_resource_test.go -package dispatching -write_package_comment=false github.com/sarchlab/mgpusim/v4/amd/timing/cp/internal/resource CUResourcePool,CUResource
//

package dispatching

import (
	reflect "reflect"

	sim "github.com/sarchlab/akita/v4/sim"
	kernels "github.com/sarchlab/mgpusim/v4/amd/kernels"
	resource "github.com/sarchlab/mgpusim/v4/amd/timing/cp/internal/resource"
	gomock "go.uber.org/mock/gomock"
)

// MockCUResourcePool is a mock of CUResourcePool interface.
type MockCUResourcePool struct {
	ctrl     *gomock.Controller
	recorder *MockCUResourcePoolMockRecorder
	isgomock struct{}
}

// MockCUResourcePoolMockRecorder is the mock recorder for MockCUResourcePool.
type MockCUResourcePoolMockRecorder struct {
	mock *MockCUResourcePool
}

// NewMockCUResourcePool creates a new mock instance.
func NewMockCUResourcePool(ctrl *gomock.Controller) *MockCUResourcePool {
	mock := &MockCUResourcePool{ctrl: ctrl}
	mock.recorder = &MockCUResourcePoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCUResourcePool) EXPECT() *MockCUResourcePoolMockRecorder {
	return m.recorder
}

// GetCU mocks base method.
func (m *MockCUResourcePool) GetCU(i int) resource.CUResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCU", i)
	ret0, _ := ret[0].(resource.CUResource)
	return ret0
}

// GetCU indicates an expected call of GetCU.
func (mr *MockCUResourcePoolMockRecorder) GetCU(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCU", reflect.TypeOf((*MockCUResourcePool)(nil).GetCU), i)
}

// NumCU mocks base method.
func (m *MockCUResourcePool) NumCU() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumCU")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumCU indicates an expected call of NumCU.
func (mr *MockCUResourcePoolMockRecorder) NumCU() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumCU", reflect.TypeOf((*MockCUResourcePool)(nil).NumCU))
}

// RegisterCU mocks base method.
func (m *MockCUResourcePool) RegisterCU(cu resource.DispatchableCU) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterCU", cu)
}

// RegisterCU indicates an expected call of RegisterCU.
func (mr *MockCUResourcePoolMockRecorder) RegisterCU(cu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCU", reflect.TypeOf((*MockCUResourcePool)(nil).RegisterCU), cu)
}

// MockCUResource is a mock of CUResource interface.
type MockCUResource struct {
	ctrl     *gomock.Controller
	recorder *MockCUResourceMockRecorder
	isgomock struct{}
}

// MockCUResourceMockRecorder is the mock recorder for MockCUResource.
type MockCUResourceMockRecorder struct {
	mock *MockCUResource
}

// NewMockCUResource creates a new mock instance.
func NewMockCUResource(ctrl *gomock.Controller) *MockCUResource {
	mock := &MockCUResource{ctrl: ctrl}
	mock.recorder = &MockCUResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCUResource) EXPECT() *MockCUResourceMockRecorder {
	return m.recorder
}

// DispatchingPort mocks base method.
func (m *MockCUResource) DispatchingPort() sim.RemotePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchingPort")
	ret0, _ := ret[0].(sim.RemotePort)
	return ret0
}

// DispatchingPort indicates an expected call of DispatchingPort.
func (mr *MockCUResourceMockRecorder) DispatchingPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchingPort", reflect.TypeOf((*MockCUResource)(nil).DispatchingPort))
}

// FreeResourcesForWG mocks base method.
func (m *MockCUResource) FreeResourcesForWG(wg *kernels.WorkGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FreeResourcesForWG", wg)
}

// FreeResourcesForWG indicates an expected call of FreeResourcesForWG.
func (mr *MockCUResourceMockRecorder) FreeResourcesForWG(wg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeResourcesForWG", reflect.TypeOf((*MockCUResource)(nil).FreeResourcesForWG), wg)
}

// ReserveResourceForWG mocks base method.
func (m *MockCUResource) ReserveResourceForWG(wg *kernels.WorkGroup) ([]resource.WfLocation, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveResourceForWG", wg)
	ret0, _ := ret[0].([]resource.WfLocation)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ReserveResourceForWG indicates an expected call of ReserveResourceForWG.
func (mr *MockCUResourceMockRecorder) ReserveResourceForWG(wg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveResourceForWG", reflect.TypeOf((*MockCUResource)(nil).ReserveResourceForWG), wg)
}
