// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sarchlab/mgpusim/v4/amd/timing/cp/internal/dispatching (interfaces: Dispatcher)
//
// Generated by this command:
//
//	mockgen -destination mock_dispatching_test.go -package cp -write_package_comment=false github.com/sarchlab/mgpusim/v4/amd/timing/cp/internal/dispatching Dispatcher
//

package cp

import (
	reflect "reflect"

	sim "github.com/sarchlab/akita/v4/sim"
	protocol "github.com/sarchlab/mgpusim/v4/amd/protocol"
	resource "github.com/sarchlab/mgpusim/v4/amd/timing/cp/internal/resource"
	gomock "go.uber.org/mock/gomock"
)

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
	isgomock struct{}
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// AcceptHook mocks base method.
func (m *MockDispatcher) AcceptHook(hook sim.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptHook", hook)
}

// AcceptHook indicates an expected call of AcceptHook.
func (mr *MockDispatcherMockRecorder) AcceptHook(hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptHook", reflect.TypeOf((*MockDispatcher)(nil).AcceptHook), hook)
}

// Hooks mocks base method.
func (m *MockDispatcher) Hooks() []sim.Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hooks")
	ret0, _ := ret[0].([]sim.Hook)
	return ret0
}

// Hooks indicates an expected call of Hooks.
func (mr *MockDispatcherMockRecorder) Hooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hooks", reflect.TypeOf((*MockDispatcher)(nil).Hooks))
}

// InvokeHook mocks base method.
func (m *MockDispatcher) InvokeHook(arg0 sim.HookCtx) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvokeHook", arg0)
}

// InvokeHook indicates an expected call of InvokeHook.
func (mr *MockDispatcherMockRecorder) InvokeHook(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeHook", reflect.TypeOf((*MockDispatcher)(nil).InvokeHook), arg0)
}

// IsDispatching mocks base method.
func (m *MockDispatcher) IsDispatching() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDispatching")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDispatching indicates an expected call of IsDispatching.
func (mr *MockDispatcherMockRecorder) IsDispatching() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDispatching", reflect.TypeOf((*MockDispatcher)(nil).IsDispatching))
}

// Name mocks base method.
func (m *MockDispatcher) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDispatcherMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDispatcher)(nil).Name))
}

// NumHooks mocks base method.
func (m *MockDispatcher) NumHooks() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumHooks")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumHooks indicates an expected call of NumHooks.
func (mr *MockDispatcherMockRecorder) NumHooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumHooks", reflect.TypeOf((*MockDispatcher)(nil).NumHooks))
}

// RegisterCU mocks base method.
func (m *MockDispatcher) RegisterCU(cu resource.DispatchableCU) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterCU", cu)
}

// RegisterCU indicates an expected call of RegisterCU.
func (mr *MockDispatcherMockRecorder) RegisterCU(cu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCU", reflect.TypeOf((*MockDispatcher)(nil).RegisterCU), cu)
}

// StartDispatching mocks base method.
func (m *MockDispatcher) StartDispatching(req *protocol.LaunchKernelReq) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartDispatching", req)
}

// StartDispatching indicates an expected call of StartDispatching.
func (mr *MockDispatcherMockRecorder) StartDispatching(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDispatching", reflect.TypeOf((*MockDispatcher)(nil).StartDispatching), req)
}

// Tick mocks base method.
func (m *MockDispatcher) Tick() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tick")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Tick indicates an expected call of Tick.
func (mr *MockDispatcherMockRecorder) Tick() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tick", reflect.TypeOf((*MockDispatcher)(nil).Tick))
}
